apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: defectdojo-ingress
  namespace: defectdojo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - defectdojo.35.195.231.227.nip.io
      secretName: defectdojo-tls
  rules:
    - host: defectdojo.35.195.231.227.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: defectdojo-django
                port:
                  number: 80
