apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-service:5432/defectdojo_ai"
  GROQ_API_KEY: "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"
  GITHUB_TOKEN: "ghp_3M2IMqvL7kCG6uUbi4Jgo2P7GzCrP02a7mHj"
  JWT_SECRET: "change_me"
  DEFECTDOJO_URL: "https://retributive-matilde-bloomier.ngrok-free.dev"
  DEFECTDOJO_API_KEY: "5f846a11df9ffa1a338a1d034c758a4d08c46274"
  CLIENT_ORIGIN: "https://35.195.231.227.nip.io"
  GITHUB_OWNER: "YoussefHalleb"
  GITHUB_REPO: "Universal"
  GITHUB_WORKFLOW_FILE: "devsecops-universal.yml"
  PORT: "5000"
