apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gcr.io/secdashboard-pfe/backend:654647e52d19fe2b9c40c6a0085e6268d31f7765
          ports:
            - containerPort: 5000

          # 🔐 Variables depuis secret (DB, JWT, etc.)
          envFrom:
            - secretRef:
                name: backend-secret

          # 🔑 Variables Vertex AI (IMPORTANT)
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gcp-key.json
            - name: GCP_PROJECT_ID
              value: secdashboard-pfe
            - name: VERTEX_ENGINE_ID
              value: owasp-rag-search_1776940899539
            - name: VERTEX_DATASTORE_ID
              value: owasp-security-docs_1776940659305
            - name: VERTEX_LOCATION
              value: global

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: gcp-key
              mountPath: /secrets
              readOnly: true

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: gcp-key
          secret:
            secretName: gcp-key
