apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: back-sa
      containers:
        - name: backend
          image: gcr.io/secdashboard-pfe/backend:b53a2c7b2021119351e6c315050bc0c3f5c41f2a
          ports:
            - containerPort: 5000

          envFrom:
            - secretRef:
                name: backend-secret

          env:
            - name: GCP_PROJECT_ID
              value: secdashboard-pfe
            - name: VERTEX_ENGINE_ID
              value: owasp-rag-search_1776940899539
            - name: VERTEX_DATASTORE_ID
              value: owasp-security-docs_1776940659305
            - name: VERTEX_LOCATION
              value: global

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc
