apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/secdashboard-pfe/frontend:b37f010d9f8607786da65a2ecfe368bb4a460f3b
          ports:
            - containerPort: 80
