apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/secdashboard-pfe/frontend:b836980b54118f6972537c45cb4a42dd5fdb0369
          ports:
            - containerPort: 80
