apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/secdashboard-pfe/frontend:ab22c0ef4e10edcdec8373177997011d675906ca
          ports:
            - containerPort: 80
