apiVersion: v1
kind: ServiceAccount
metadata:
  name: ia-agent
  namespace: production
  annotations:
    # Workload Identity : lie ce ServiceAccount au compte GCP
    iam.gke.io/gcp-service-account: ia-agent@TON_PROJECT_ID.iam.gserviceaccount.com
